### ISSUE TITLE
Improve re-throwing of test-loader failures

### ISSUE THREAD

**Issue by trentmwillis** [ember-cli/ember-cli-qunit#100]
Currently, if a test module fails to load it is ["re-thrown" as a failing QUnit test](https://github.com/ember-cli/ember-cli-qunit/blob/115d56bff12ad01ef08c34a1ae9f9011e7e6904b/vendor/ember-cli-qunit/test-loader.js#L33-L38). This has caused problems for some developers, however, as it means test-loader failures do not show up at all when using either the `filter` or `module` options to limit the tests you run. This is very non-obvious unless you understand how the test-loader works.

I don't know the background of this feature, but here are a few alternative approaches:

1. Actually re-throw errors when they're first encountered (prevents it from being tied to QUnit's behavior),
2. Coalesce all loading failures into a [QUnit.done](https://api.qunitjs.com/QUnit.done/) callback (that way they will run regardless of filters), or
3. Ensure the module/test name we give the failures takes into account an enabled filters

cc @pete-the-pete

**Comment by ppcano** [comment]
I agree, default behaviour is non obvious. I encountered the same situation at ember-cli/ember-cli-test-loader#25

**Comment by trentmwillis** [comment]
Fixed via #117.
