### ISSUE TITLE
You cannot use the same root element (#ember-testing) multiple times in an Ember.Application

### ISSUE THREAD

**Issue by sajt** [ember-cli/ember-cli-qunit#101]
I get the following errors in a lot of Integration and acceptance tests:
`Error: Assertion Failed: You cannot use the same root element (#ember-testing) multiple times in an Ember.Application`
and 
`Promise rejected before it renders: Assertion Failed: You cannot use the same root element (#ember-testing) multiple times in an Ember.Application`

My tests now is what the `ember g` generated, I do not changed anything on it.

**Comment by sajt** [comment]
I think here is the solution: https://github.com/emberjs/ember.js/issues/11738

**Comment by sajt** [comment]
No. I upgraded my all project to Ember 2 and everything is the latest version (I hope...) but I got the same error.

**Comment by trentmwillis** [comment]
@sajt that usually means an earlier test didn't clean up properly (usually due to an error being thrown).

**Comment by sajt** [comment]
Now it is working, but I do not know why :)
