### ISSUE TITLE
version 1.2.2 throws error when building 

### ISSUE THREAD

**Issue by danielspaniel** [ember-cli/ember-cli-qunit#103]
TypeError: Cannot read property 'addon' of undefined 

 at Class.module.exports.lintTree (/Users/danielsudol/projects/ember-data-factory-guy/node_modules/ember-cli-qunit/index.js:192:43)

 I am using ember-cli  2.3.0-beta.2 ( not sure if it's related )

**Comment by cigoe** [comment]
I just hit this as well and fixed it by manually downgrading ember-cli-qunit to 1.2.1 in package.json

I'm on ember-cli 1.13.15

**Comment by danielspaniel** [comment]
same here .. on the downgrade

**Comment by nanuxbe** [comment]
Same here (ember-cli 2.3.0-beta.2 and ember-cli 2.3.0-beta.1).

Replacing line 192 with:
`var lintingAddonExists = !this.projects || this.projects.addon.find(function(addon) {`
fixes the error but I haven't looked further at the code so I don't know if this is a valid patch or not

**Comment by rwjblue** [comment]
Should be fixed by https://github.com/ember-cli/ember-cli-qunit/pull/104 once it's updated to address my comment.

**Comment by rwjblue** [comment]
Should be fixed in 1.2.3, please test and confirm

**Comment by danielspaniel** [comment]
not quite fixed yet

I now get this

```undefined is not a function
TypeError: undefined is not a function
    at Class.module.exports.lintTree (/Users/danielsudol/projects/ember-data-factory-guy/node_modules/ember-cli-qunit/index.js:192:50)
    at /Users/danielsudol/projects/ember-data-factory-guy/node_modules/ember-cli/lib/broccoli/ember-app.js:548:20```

**Comment by kostefan** [comment]
same here. try this:

    var lintingAddonExists = this.project.addons.map(function(addon) {
      return addonContext !== addon && addon.lintTree && addon.isDefaultJSLinter;
    }).filter(Boolean);

**Comment by rwjblue** [comment]
Ugh! Yes, `Array.prototype.find` isn't available on node 0.10/0.12. :cry:

**Comment by rwjblue** [comment]
OK, released 1.2.4, after testing against node 0.10/0.12/4.3/5.6.

**Comment by kostefan** [comment]
yes! solution for node 0.12 and ember-cli 1.13.15
thanks

**Comment by rwjblue** [comment]
Sorry for the extra work on a Sunday.  We really need to get this repo under test. :disappointed:

**Comment by nanuxbe** [comment]
@rwjblue don't worry about the extra work and thank you for the very fast response (and the great work in general)
