### ISSUE TITLE
Missing stacktrace from qunit output

### ISSUE THREAD

**Issue by promisedlandt** [ember-cli/ember-cli-qunit#106]
I updated my ember from 2.3.0 to 2.3.1, and now I'm missing the stack trace from my failing QUnit tests.

I'm new to ember, and I have no idea whether this is a problem with ember-cli, ember-cli-qunit, ember-cli-test-loader, qunit, testem or something completely different.

Example output: `not ok 43 PhantomJS 2.1 - Integration | Component | dominions4 pretender calculator pretender selection: clicking a pretender calls onPretenderSelected with the selected pretender`. 
There used be a few lines after this line with more details of the error, but not any more after the update.
The test failed before as well, that's fine, I just need the output to figure out why.

On advice from the ember slack, I installed testem@1.4.0 via npm (he said before that it was the version that came with ember-cli, not sure which one that was), but it didn't change anything.
Other things I've tried are:
- removing the bower / node folders, cleaning the caches and reinstalling them
- running the generators for ember-cli-qunit and ember-cli

One other user in the slack channel mention he had the same problem, but he had not found a solution either.

I have generated a gist with `package.json` and `bower.json` [here](https://gist.github.com/promisedlandt/b73bc05cee6fe0aaab45), please let me know if you need anything else.

**Comment by stefanpenner** [comment]
if you have a chance to provide a repo with a sample app that demonstrates this issue, it will help someone more quickly investigate.

**Comment by promisedlandt** [comment]
Right - should have thought of that.

I have uploaded everything [here](https://github.com/promisedlandt/dominionsserver/tree/master/ember_apps/dominionsserver)

**Comment by promisedlandt** [comment]
I neded up reinstalling npm, bower, ember-cli, removing the bower / npm folders, cleaning the caches for npm / bower and reinstalling everything. I have stacktraces again, no idea why.
