### ISSUE TITLE
Suggest changing message to upgrade ember-cli-loader from 1.0.0 to 0.2.2

### ISSUE THREAD

**Issue by alanwong22** [ember-cli/ember-cli-qunit#109]
Our Ember test resulted in the following error to upgrade to ember-cli-loader to 1.0.0

`not ok 1 PhantomJS 2.1 - global failure
    ---
        actual: >
            null
        message: >
            Error: You must upgrade your version of ember-cli-test-loader to 1.0.0 to use this version of ember-cli-qunit
        Log: |
    ...`

Which caused this after the upgrade:

`Build failed.
ENOENT, no such file or directory '/.../tmp/funnel-input_base_path-Vp2y8Sjt.tmp/0/bower_components/ember-cli-test-loader/test-loader.js'
Error: ENOENT, no such file or directory '/.../tmp/funnel-input_base_path-Vp2y8Sjt.tmp/0/bower_components/ember-cli-test-loader/test-loader.js'`

It turns out that the Current Release version of ember-cli-loader is actually 0.2.2. Downgrading the version fixed the test suite.

System Info:
ember version: 1.13.8
node: 0.12.4
npm: 2.13.4
os: darwin x64

**Comment by trentmwillis** [comment]
@alanwong22 I just opened a PR (#112) to fix this by not needing to upgrade at all. Does that seem reasonable?

**Comment by rwjblue** [comment]
Fixed by https://github.com/ember-cli/ember-cli-qunit/pull/112.
