### ISSUE TITLE
Breaking change in 1.4.0, requiring ember-cli-test-loader >= 1.0.0

### ISSUE THREAD

**Issue by john-kurkowski** [ember-cli/ember-cli-qunit#110]
Ember CLI boilerplate pinned me to the carat version of ember-cli-qunit in package.json:

```json
  "ember-cli-qunit": "^1.0.4",
```

And an exact version of ember-cli-test-loader in bower.json:

```json
  "ember-cli-test-loader": "ember-cli-test-loader#0.1.3",
```

Ran a clean `npm i` install recently, and am now getting this runtime error:

```
You must upgrade your version of ember-cli-test-loader to 1.0.0 to use this version of ember-cli-qunit
```

Can you ease this restriction in ember-cli-qunit 1.x? Or bump the major version of ember-cli-qunit, to indicate backwards incompatibility?

**Comment by john-kurkowski** [comment]
Related to #109?

**Comment by trentmwillis** [comment]
We've encountered this as well. The breakage was introduced in #108, but seems like it could be made to be backwards compatible. I'll look into submitting a patch to get us some back-compat.

**Comment by rwjblue** [comment]
Thanks @trentmwillis

**Comment by rwjblue** [comment]
Fixed by https://github.com/ember-cli/ember-cli-qunit/pull/112
