### ISSUE TITLE
disable JSCS options not working in v2.1.0

### ISSUE THREAD

**Issue by danielspaniel** [ember-cli/ember-cli-qunit#125]
When I upgraded to 3.0.1 the nojscs option was ignored .. and when I downgraded to 1.4.2 it was cheerfully accepted and I no longer see the JSCS files in the test modules list. 
 Kinda strange, but ? maybe something happened between then and now?

**Comment by trentmwillis** [comment]
The latest release of `ember-cli-qunit` is `2.1.0`, so I'm unsure what behavior you're seeing as `3.0.1` doesn't exist.

**Comment by danielspaniel** [comment]
sorry I meant 2.1.0 
 ok .. sure .. that is fine to submit on ember-suave  I was not sure who controlled those options in qunit, like nolint ( Disable jshint ) ,   nojsjcs ( Disable JSCS ) .. etc ..

**Comment by trentmwillis** [comment]
The `nolint` option is part of this addon ([as defined here](https://github.com/ember-cli/ember-cli-qunit/blob/6a4d5c549fdb2d9b18c122e94b82de3060299d71/vendor/ember-cli-qunit/qunit-configuration.js#L4)), but the `nojscs` option is part of ember-suave ([as defined here](https://github.com/DockYard/ember-suave/blob/e2d3c6b9aa41b51eaac61b4c6016232d17621fef/vendor/ember-suave/qunit-configuration.js#L3)).

I tend to think this is related to [this open PR on ember-suave](https://github.com/DockYard/ember-suave/pull/131).

**Comment by danielspaniel** [comment]
ooo .. good catch . .. i forgot to check the open PR's

**Comment by brzpegasus** [comment]
@danielspaniel This should be resolved with the latest version of `ember-suave`.

**Comment by ashoksudani** [comment]
you can disable jscs simply by passing option as defined at :https://github.com/kellyselden/broccoli-jscs

var app = new EmberApp({
  jscsOptions: {
    enabled: false,
    disableTestGenerator: true
  }
});

this will not check for any jscs test across files..
