### ISSUE TITLE
No test cases to run

### ISSUE THREAD

**Issue by hckhanh** [ember-cli/ember-cli-qunit#138]
When I download `v2.2.0`. I realize that it can only run with `ember test --server` but not for command line (`ember test`). So my Travis build is failed, because there are **no test cases to run**.

**Comment by rwjblue** [comment]
@hckhanh - Can you test with 2.2.1?

**Comment by hckhanh** [comment]
@rwjblue I have seen it 21 minutes. Let's me try it. Thanks :+1:

**Comment by hckhanh** [comment]
Now It works perfectly. Thank you :smile:
