### ISSUE TITLE
Upgrade to latest qunitjs

### ISSUE THREAD

**Issue by ms** [ember-cli/ember-cli-qunit#141]
The latest qunitjs version supports selecting multiple modules. It'd be great to use the latest qunitjs in package.json to take advantage of that (and I'm sure other) features.

**Comment by trentmwillis** [comment]
There is an effort underway to get QUnit 2 support in Ember land, but it's non-trivial since QUnit 2's API changes broke some assumptions that Ember has about test setup. Will keep you posted!

**Comment by rwjblue** [comment]
Landed in https://github.com/ember-cli/ember-cli-qunit/pull/134 and released in 3.0.0-beta.1.
