### ISSUE TITLE
Using test from shims produces deprecation warnings

### ISSUE THREAD

**Issue by mdentremont** [ember-cli/ember-cli-qunit#148]
```
Error: The global `test` is removed in QUnit 2.0.
Details in our upgrade guide at https://qunitjs.com/upgrade-guide-2.x/
Error: The global `test` is removed in QUnit 2.0.
Details in our upgrade guide at https://qunitjs.com/upgrade-guide-2.x/
```

**Comment by rwjblue** [comment]
Can you provide a demo/example repo that shows this?

The thing that is returned from `import { test } from 'qunit';` is not the global `test`, it is `QUnit.test` (from [here](https://github.com/rwjblue/ember-qunit/blob/master/lib/qunit.js#L4)).

**Comment by mdentremont** [comment]
Sorry, I was still trying to sort out my environment before coming back and
closing this and never got to it. I doubt that it is an issue on your end
and will likely close this tomorrow.

**Comment by mdentremont** [comment]
@rwjblue Confirmed that it was my fault, I missed one test out of thousands :)
