### ISSUE TITLE
ember test not running entire test suite with v2.2.2

### ISSUE THREAD

**Issue by joebartels** [ember-cli/ember-cli-qunit#149]
`ember test` isn't running tests for me with **v2.2.2**

**v2.2.1** works 

There's only 1 change that looks of any significance (see diff). Not sure what I can share that would be useful for debugging but if you need more details from me I'll be happy to share.
https://github.com/ember-cli/ember-cli-qunit/compare/v2.2.1...v2.2.2

on the flip side, doing `ember serve` and visiting **localhost:4200/tests** works as usual.

```
1..0
# tests 0
# pass  0
# skip  0
# fail  0

# ok
No tests were run, please check whether any errors occurred in the page (ember test --server) and ensure that you have a test launcher (e.g. PhantomJS) enabled.
```

package.json
```
  "devDependencies": {
    "broccoli-asset-rev": "^2.4.2",
    "ember-ajax": "2.4.1",
    "ember-cli": "2.6.3",
    "ember-cli-app-version": "^1.0.0",
    "ember-cli-babel": "^5.1.6",
    "ember-cli-content-for-config": "1.0.1",
    "ember-cli-dependency-checker": "^1.2.0",
    "ember-cli-htmlbars": "^1.0.3",
    "ember-cli-htmlbars-inline-precompile": "^0.3.1",
    "ember-cli-inject-live-reload": "^1.4.0",
    "ember-cli-preloader": "0.1.3",
    "ember-cli-qunit": "2.2.2",
    "ember-cli-release": "^0.2.9",
    "ember-cli-sri": "^2.1.0",
    "ember-data": "2.6.1",
    "ember-export-application-global": "^1.0.5",
    "ember-load-initializers": "0.5.1",
    "ember-resolver": "^2.0.3"
  },
```

bower.json
```
  "dependencies": {
    "ember": "2.6.1",
    "ember-cli-shims": "0.1.0",
    "ember-cli-test-loader": "0.2.1",
    "ember-qunit-notifications": "0.1.0",
    "es5-shim": "^4.0.5"
  },
```

**Comment by rwjblue** [comment]
Seems conceptually similar to https://github.com/ember-cli/ember-cli-qunit/issues/147, but I don't see blanket as one of your deps.

**Comment by joebartels** [comment]
ah. I was trying to clean up the noise so I removed all ember add-ons that I [thought I] included manually.
In reality blanket is also included:
```
"ember-cli-blanket": "0.9.5"
```

Thank you for linking #147
