### ISSUE TITLE
Acceptance test container not visible unless addon options specified in ember-cli-build.js file

### ISSUE THREAD

**Issue by schickm** [ember-cli/ember-cli-qunit#150]
Unless I specify options like below, I never see my acceptance testing container in the qunit test runner.

in `ember-cli-build.js`:
```
var app = new EmberApp(defaults, {
    'ember-cli-qunit': {
        disableContainerStyles: false,
    },
});
```

![with addon options specified](https://cloud.githubusercontent.com/assets/197222/18759247/7f4597da-80b0-11e6-8d0f-8d907f23d2a0.png)

Without it specified we get no test runner visible:
```
var app = new EmberApp(defaults, {
});
```
![without options specified](https://cloud.githubusercontent.com/assets/197222/18759293/b21f1f64-80b0-11e6-87db-f9a7ef24508b.png)

The issue seems to be that the stylesheet which displays the container only gets inserted if you have the addon options specified...this seems like a strange default and isn't mentioned anywhere
https://github.com/ember-cli/ember-cli-qunit/blob/e6a594f7442741438674904dfbc3c462e766c310/index.js#L88

Above screenshots were taken with a fresh Ember app with just a single generated acceptance test.

Console Output:
```
Ember      : 2.8.1
Ember Data : 2.8.0
jQuery     : 3.1.0
```

here's my package.json:
```
{
  "name": "dummy",
  "version": "0.0.0",
  "description": "Small description for dummy goes here",
  "private": true,
  "directories": {
    "doc": "doc",
    "test": "tests"
  },
  "scripts": {
    "build": "ember build",
    "start": "ember server",
    "test": "ember test"
  },
  "repository": "",
  "engines": {
    "node": ">= 0.10.0"
  },
  "author": "",
  "license": "MIT",
  "devDependencies": {
    "broccoli-asset-rev": "^2.4.2",
    "ember-ajax": "^2.0.1",
    "ember-cli": "2.8.0",
    "ember-cli-app-version": "^1.0.0",
    "ember-cli-babel": "^5.1.6",
    "ember-cli-dependency-checker": "^1.2.0",
    "ember-cli-htmlbars": "^1.0.3",
    "ember-cli-htmlbars-inline-precompile": "^0.3.1",
    "ember-cli-inject-live-reload": "^1.4.0",
    "ember-cli-jshint": "^1.0.0",
    "ember-cli-qunit": "^2.1.0",
    "ember-cli-release": "^0.2.9",
    "ember-cli-sri": "^2.1.0",
    "ember-cli-test-loader": "^1.1.0",
    "ember-cli-uglify": "^1.2.0",
    "ember-data": "^2.8.0",
    "ember-export-application-global": "^1.0.5",
    "ember-load-initializers": "^0.5.1",
    "ember-resolver": "^2.0.3",
    "ember-welcome-page": "^1.0.1",
    "loader.js": "^4.0.1"
  }
}
```

bower.json:
```
{
  "name": "dummy",
  "dependencies": {
    "ember": "~2.8.0",
    "ember-cli-shims": "0.1.1"
  }
}
```

PS.  Love that new developer mode with full screen viewing of the acceptance test container - great addition 🎉

**Comment by nathanhammond** [comment]
- [You did indeed find the lines in question.](https://github.com/ember-cli/ember-cli-qunit/blob/e6a594f7442741438674904dfbc3c462e766c310/index.js#L86-L88)
- [We don't have any default config for this addon inside of the app blueprint.](https://github.com/ember-cli/ember-cli/blob/master/blueprints/app/files/ember-cli-build.js)

[Would you be willing to document this inside of README.md?](https://github.com/ember-cli/ember-cli-qunit/blob/master/README.md)

Thanks!

**Comment by schickm** [comment]
Thanks for the detailed response!  I'm a little confused about the [link to the default options inside of lib/broccoli/ember-app.js](https://github.com/rwjblue/ember-cli/blob/a0087f624f161b40136c2c4a4bbb26cc638db2fa/lib/broccoli/ember-app.js#L119).  That points to rwjblue's fork of ember-cli and not the one published to npm ([which doesn't include those default options](https://github.com/ember-cli/ember-cli/blob/master/lib/broccoli/ember-app.js#L218))

So...I'm happy to document this in the README.md, but I'm still a little confused about what the expected behavior is for a newly generated ember app.  Should I be opening an issue on ember-cli instead?

**Comment by nathanhammond** [comment]
Whoa, good catch. I thought that code still existed and simply grabbed a link to it from somewhere while not paying attention. https://github.com/ember-cli/ember-cli/pull/4928 got ninja-merged on me.

The default should be that we include the container styles. The only time we don't include container styles is when `addonOptions` exists and `disableContainerStyles` is set to something other than `false`.

So:
`if (addonOptions && addonOptions.disableContainerStyles === false) {`

Should be:
`if (!addonOptions || addonOptions.disableContainerStyles !== false) {`

This is indeed a bug. Would you please submit a PR since you did the research on this?

**Comment by nathanhammond** [comment]
Fixed. Released in v2.2.3 and v3.0.2. Thank you @schickm for identifying and filing an issue!

**Comment by schickm** [comment]
No problem! Sorry I didn't get around to submitting that fix.

**Comment by nathanhammond** [comment]
Your detailed issue made it clear what was going on. I'm incredibly grateful.
