### ISSUE TITLE
Provide ability to inject html into test-body

### ISSUE THREAD

**Issue by sangm** [ember-cli/ember-cli-qunit#154]
For some context:

Ember events are only attached to  `rootElement` [event_dispatcher](https://github.com/emberjs/ember.js/blob/master/packages/ember-views/lib/system/event_dispatcher.js#L90)

Within the testing environment, `rootElement` resolves to `#ember-testing`. [ember-test-helpers](https://github.com/emberjs/ember-test-helpers/blob/77f9a53da9d8c19a85b3122788caadbcc59274c2/tests/test-module-for-acceptance-test.js#L13)

Let's assume I have an addon that I would like to have it tested, but it generates content through `content-for`.

```
// index.html
<html>
  ...

  {{content-for 'foo-want-this-tested'}}
  {{content-for 'test-body'}}
</html>
```

Obviously, I can't test the contents of `foo-want-this-tested`.
Would love to work on this, but if there are already options on how to achieve this what is it, or can I get some guidance on implementation? `contentFor` seems very limited

**Comment by nathanhammond** [comment]
@sangm Your goal is to move the global nav into the testing container, confirm?

Assuming that I've successfully guessed your goal the workaround that comes to mind is `insertContentForTestBody: false` and insert your own content via `{{content-for 'test-body'}}`. You can also read the content from the template in `ember-cli-qunit` to guarantee that you remain consistent with upstream. We could design an improved `content-for` hook which allowed blocks:

Input:
```
{{content-for 'test-body'}}
  Bonus content.
{{/content-for}}
```

Template usage:
```test-body.html
<foo>{{yield}}</foo>
```

Would you be interested in writing a PR for this to Ember CLI?

**Comment by sangm** [comment]
Of course! I'll start looking into it

**Comment by nathanhammond** [comment]
Note: that PR is likely going to need to be coupled with an RFC, but I'd like to see how invasive of a change it would be. I've already thought of a few weird things with my first idea: `test-body` is invoked on _each_ addon, all of them have an opportunity to respond. So my first thought isn't good enough.

So this still needs design work.

**Comment by sangm** [comment]
You are talking about this?

**Comment by sangm** [comment]
So, here's the general idea from a quick look:

`ember-cli` uses [`broccoli-config-replace` to match `content-for`](https://github.com/ember-cli/ember-cli/blob/fa03e267b0742aac51a9431b54c0476215c41bec/lib/broccoli/ember-app.js#L737) regexp and executes `contentFor`. Looking at [broccoli-config-replace](https://github.com/ember-cli/broccoli-config-replace/blob/ec5e344eba3680127d4471645148eceee29c4398/index.js#L76), need to make some changes there too.

One concern is, @nathanhammond deprecated this lol https://github.com/ember-cli/ember-cli/blob/fa03e267b0742aac51a9431b54c0476215c41bec/lib/broccoli/ember-app.js#L1712. Ignoring that for now,

1. Make changes to `broccoli-config-replace` to support multiple regex matches.
2. Modify `ember-cli/lib/broccoli/ember-app.js` and have something like: 
```javascript
    /* matches {{content-for 'test-body'}} foo bar {{/content-for}} */
    match: /\{\{content-for ['"](.+)["']\}\}([\s\S]+)\{\{\/content-for\}\}/g,
    replacement: this.contentFor.bind(this)
```
3. Make changes in [ember-cli-qunit's `content-for`](https://github.com/ember-cli/ember-cli-qunit/blob/638d3ff55d67fb756bc0a750c417373963942fa9/index.js#L123)

Let me know what you think!

**Comment by nathanhammond** [comment]
@sangm [I only deprecated these.](https://github.com/ember-cli/ember-cli/blob/fa03e267b0742aac51a9431b54c0476215c41bec/lib/broccoli/ember-app.js#L1699) ... they are too dangerous and encourage people to do bad things. Not all `contentFor` behavior is deprecated.

How do you propose to {{yield}} only into the `contentFor('test-body')` hook for `ember-cli-qunit`? Multiple addons are able to register for that hook. By reducing if you happen to come _after_ you have a reference to the current content.

(I'd forgotten that the hook inside of any addon has access to the currently-calculated `content` at that point. That alone is enough to accomplish your original goal.)

**Comment by sangm** [comment]
I figured we add support for `{{yield}}` to `content-for`, and `ember-cli-qunit` could just use the feature

**Comment by nathanhammond** [comment]
Yes, but what if `my-cool-testing-addon` also used `contentFor('test-body')` in addition? See: https://github.com/nathanhammond/ember-capture/blob/master/index.js#L33-L41

**Comment by sangm** [comment]
I see...

In `ember-cli-qunit`, I can iterate through all the content and have an "include" flag within config object.. 

Although I think the `{{yield}}` is cleaner and consistent with handlebars/ember...

What do you suggest?

**Comment by sangm** [comment]
Bump @nathanhammond

**Comment by trentmwillis** [comment]
I would like to raise the question of "how often do we feel this is needed?"

I'm concerned that the use case of rendering content external to the application and then wiring it up to the application is an exceedingly rare use case. In which case I would argue that a one-off solution for the consumer is better than adding additional logic to this addon or Ember-CLI proper.

**Comment by trentmwillis** [comment]
This seems to have gone stale, and I believe a solution was found in user land, so I'm going to close for now.
