### ISSUE TITLE
Error: The global `module` is removed in QUnit 2.0.

### ISSUE THREAD

**Issue by rwwagner90** [ember-cli/ember-cli-qunit#158]
It seems that unit tests are trying to pull in the wrong module somehow? They seem to be the only thing that pulls directly from qunit. 

`import { module, test } from 'qunit';`

This is generated when running `ember g util foo`

Perhaps we just need to fix the blueprint to pull in module differently? I am unsure.

Error:
```
stack: >
            http://localhost:7357/assets/test-support.js:7092
        message: >
            Error: 
            Error: The global `module` is removed in QUnit 2.0.
            Details in our upgrade guide at https://qunitjs.com/upgrade-guide-2.x/
```

**Comment by Turbo87** [comment]
unfortunately the following commands are not able to reproduce the issue:

```
ember new foobar
ember g util foo
ember test
```

**Comment by Turbo87** [comment]
> rwwagner90 [16:58]  
> @tbieniek seems the issue was actually with https://github.com/sir-dunxalot/ember-cli-sass-lint

**Comment by jamesarosen** [comment]
I think this is a problem with this library, at least in v3.0.2. It adds QUnit v2.x to the project, but [still generates a 1.x-style test file](https://github.com/ember-cli/ember-cli-qunit/blob/v3.0.2/index.js#L135-L145).

**Comment by trentmwillis** [comment]
@jamesarosen the generated test looks correct for 2.x to me. Can you elaborate on what you think is incompatible?

**Comment by jamesarosen** [comment]
When running [ember-cli-stylelint](https://github.com/billybonks/ember-cli-stylelint), I get

```
not ok 7 PhantomJS 2.1 - TestLoader Failures: app/styles/my-stylesheet.stylelint-test: could not be loaded
    ---
        actual: >
            null
        stack: >
            http://localhost:7357/assets/test-support.js:4381:133
            http://localhost:7357/assets/tests.js:294:9
            exports@http://localhost:7357/assets/vendor.js:132:37
            requireModule@http://localhost:7357/assets/vendor.js:32:25
            require@http://localhost:7357/assets/test-support.js:7104:14
            loadModules@http://localhost:7357/assets/test-support.js:7096:21
            load@http://localhost:7357/assets/test-support.js:7126:33
            http://localhost:7357/assets/test-support.js:7009:22
        message: >
            Died on test #1 moduleLoadFailure@http://localhost:7357/assets/test-support.js:6997:17
            require@http://localhost:7357/assets/test-support.js:7106:29
            loadModules@http://localhost:7357/assets/test-support.js:7096:21
            load@http://localhost:7357/assets/test-support.js:7126:33
            http://localhost:7357/assets/test-support.js:7009:22: The global `module` is removed in QUnit 2.0.
            Details in our upgrade guide at https://qunitjs.com/upgrade-guide-2.x/
        Log: |
    ...
```

[Here](https://github.com/billybonks/ember-cli-stylelint/blob/0.6.2/index.js#L47-L51) is where ember-cli-stylelint uses the `generateTestFile` API.

**Comment by trentmwillis** [comment]
Do you have a reproduction? Is the error occuring in the ember-cli-stylelint test suite?

**Comment by jamesarosen** [comment]
I'll work on a public reproduction. It's not on ember-cli-stylelint itself. It's on any project that uses it with recent versions of ember-qunit. (ember-cli-stylelint, like ember-cli-sass-lint, doesn't declare any styles; rather, it declares tests based on linting CSS files)

**Comment by jamesarosen** [comment]
AHA! The problem is in [broccoli-stylelint](https://github.com/billybonks/broccoli-stylelint/blob/0.8.3/index.js#L198-L213)

**Comment by rwwagner90** [comment]
@jamesarosen any chance you could find a similar issue in https://github.com/sir-dunxalot/broccoli-sass-lint ? 😄

**Comment by jamesarosen** [comment]
@rwwagner90 I think you just have to change `module` to `QUnit.module` and likewise for `test` here: https://github.com/sir-dunxalot/broccoli-sass-lint/blob/c158a9c2b711d443bc130bfcdee21496d42e20c8/index.js#L239-L242
