### ISSUE TITLE
Replace auto-load with "loader" function

### ISSUE THREAD

**Issue by trentmwillis** [ember-cli/ember-cli-qunit#171]
I think we should move away from having the tests "automagically" load; I'd like to see us move to something more explicit.

We should provide a "loader" function that consumers invoke from their `test-helper.js` file. This should allow us to remove the `ready` logic and the `setTimeout` while also providing an easy way for users to reason about how their tests get loaded. It would also make it easier to pass options to `ember-cli-qunit` without having to use the global `QUnit.config` object.

Thoughts?

_Originally brought up here: https://github.com/ember-cli/ember-cli-qunit/pull/155#issuecomment-259609411_

**Comment by rwjblue** [comment]
Yes, agreed.

We should move https://github.com/ember-cli/ember-cli-qunit/blob/master/vendor/ember-cli-qunit/test-loader.js#L24-L68 to our own `addon-test-support` directory (and rewrite to use normal `import` statements), then have consumers do something like this in thier `test-helper.js`:

```js
import { TestLoader } from 'ember-cli-qunit/test-support';

TestLoader.load();
```
