### ISSUE TITLE
Qunit Issues with Ember 2.10 and Qunit 3.01

### ISSUE THREAD

**Issue by ellamenneram** [ember-cli/ember-cli-qunit#172]
Ember global 2.10
Ember cli 2.10
Ember ajax 2.4.1
ember engine 0.4.0 beta
Embet Qunit 3.0.1 We also use Sinon 

All the Qunit (Unit) tests which were working in Ember 2.6 failed in Ember 2.10. 

For ex when we are trying to unit test 

import {moduleFor , test} from 'ember-qunit';
moduleFor(' service',test name' {
})

test('name ', function(){
line x : let service=this.subject();
})

Original source is a simple service written by extending Ember.extend service .

The same test was running before but failed in line x with the upgrade. It throws error saying 
"promise rejected before "test method". Attempting to register unknown factory.

From vendor map , cannot read property subject of undefined.

**Comment by trentmwillis** [comment]
Can you please provide a minimal reproduction of your error? Either using [ember-twiddle](https://ember-twiddle.com/) or a separate github repo would be best, thanks!

**Comment by trentmwillis** [comment]
This seems to have gone stale, so I'm going to close. If you can provide further information, feel free to reopen.
