### ISSUE TITLE
ember-qunit to 2.1.2

### ISSUE THREAD

**Issue by mrkirchner** [ember-cli/ember-cli-qunit#178]
Can we get a bump of ember-qunit?  There is a fix in 2.1.1 for ember engines.

**Comment by rwjblue** [comment]
As you can see from https://github.com/ember-cli/ember-cli-qunit/blob/master/package.json#L37, we already allow 2.1.1.  If you are using `yarn` do `yarn upgrade` (or `yarn upgrade ember-qunit`), if you are using `npm` do `rm -rf node_modules && npm install`.

I don't think any changes are required here...

**Comment by mrkirchner** [comment]
Thank you
