### ISSUE TITLE
v4.0.0 just hangs

### ISSUE THREAD

**Issue by ming-codes** [ember-cli/ember-cli-qunit#184]
😦 https://travis-ci.org/ming-codes/ember-ui-kit/builds/239776698

Even in local runs too. It looks like the browser never connects.

**Comment by trentmwillis** [comment]
Did you include a call to the new `start` function? https://github.com/ember-cli/ember-cli-qunit#upgrading

**Comment by ming-codes** [comment]
😅 just saw there's a bunch of closed issues of the same problem.
