### ISSUE TITLE
Dependency on ember-cli-babel 6.0.0 beta blocks Node 7

### ISSUE THREAD

**Issue by nragaz** [ember-cli/ember-cli-qunit#185]
The package.json in ember-cli-babel 6.0.0 beta 7 only permits `node": "^4.5 || 6.* || 7.*"`. Trying to run `yarn upgrade ember-cli-babel` to 6.6.0 while running Node 8 will fail as a result.

**Comment by trentmwillis** [comment]
Thanks for the report! I've opened https://github.com/ember-cli/ember-cli-qunit/pull/186 to fix this (kind surprised it wasn't reported sooner).

**Comment by rwjblue** [comment]
This seems unlikely to be an issue here.  We depended on `^6.0.0-beta.7` which absolutely allows `6.6.0`, you most likely needed to run `yarn upgrade` to get the newest version of allowed deps.
