### ISSUE TITLE
Update to QUnit 1.16.

### ISSUE THREAD

**Issue by rwjblue** [ember-cli/ember-cli-qunit#19]
Changes:

* Assert: Add alias for throws called 'raises'
* Async: Fail assertions after existing assert.async flows are resolved
* Async: Implement assert.async
* Async: Tests are now Promise-aware
* Callbacks: Restore and warn if some logging callback gets modified
* Callbacks: Throws an error on non-function params for logging methods
* Core: change url() helper to output ?foo instead of ?foo=true
* Core: Detail modules and tests names in the logging callbacks
* Core: Implements QUnit.skip
* Core: Remove constructor
* Core: Rename config.module to config.moduleFilter
* Core: Use Error#stack without throwing when available
* Dump: Configurable limit for object depth
* HTML Reporter: Enable activating config.hidepassed from URL params
* HTML Reporter: Move QUnit.reset back to core to run it before testDone
* HTML Reporter: Output runtime of each assertion in results
* Logging: Add runtime to moduleDone
* Logging: Defer begin event till tests actually starts
* Test: Introduce order independent testId to replace testNumber
* Test: Rename module's setup/teardown to beforeEach/afterEach

**Comment by JamesMGreene** [comment]
Just a headsup: there were a few regressions found in `v1.16.0` but we've fixed all of them that we're aware of. Likely releasing a `v1.16.1` or `v1.17.0` pretty soon to clean those up.

**Comment by stefanpenner** [comment]
@JamesMGreene eta?

**Comment by JamesMGreene** [comment]
@stefanpenner: I need to add a new test for the last regression (https://github.com/jquery/qunit/pull/727) but that shouldn't take too long. New release probably in less than a week, @jzaefferer?

**Comment by jzaefferer** [comment]
Too late for a patch release, but yes, 1.17.0 should be ready in a week.
