### ISSUE TITLE
[Proposal] Deprecate qunit-notifications in favor of dropping it for ember-cli 3.0

### ISSUE THREAD

**Issue by bcardarella** [ember-cli/ember-cli-qunit#190]
qunit-notifications does some nasty hackish stuff to get added to the test suite. We haven't made use of it in some time, if people want to opt-in to it they can add it. I believe it is in the community's best interest to deprecate this plugin in anticipation of dropping it completely for the 3.0 bump at EOY

**Comment by trentmwillis** [comment]
Seems reasonable to me. I haven't really heard of anyone that relies on the functionality, so dropping the extra code would be nice.

**Comment by Turbo87** [comment]
this got removed in https://github.com/ember-cli/ember-cli-qunit/pull/191
