### ISSUE TITLE
Mouse press event stops working after upgrading to 4.1.0

### ISSUE THREAD

**Issue by billy-addepar** [ember-cli/ember-cli-qunit#199]
I am developing `ember-table` and after upgrading to `4.1.0` version, some of my tests fail. After some investigation, I found out that `pointerdown` is not triggered in test. My snippet looks like this

```
import { triggerEvent } from 'ember-native-dom-helpers';

export async function pressElement(target, x, y) {
  await triggerEvent(target, 'pointerdown', {
    clientX: x,
    clientY: y,
    button: 0,
  });
}
```

This used to work with v4.0.0 and fails with 4.1.0. Bisecting commit blames this https://github.com/ember-cli/ember-cli-qunit/commit/486d7cd7054c7eaccd178f3355dc9372e7dd5e34 as the scapegoat. In that commit, dependency on `ember-cli-test-loader` & `ember-qunit` changes. Not sure if they are related

**Comment by rwjblue** [comment]
@billy-addepar - Can you share a demo that we can use to reproduce the issue?

**Comment by billy-addepar** [comment]
@rwjblue  Thanks for your prompt reply. After trial & error, I found a bug in my code. Sorry for the confusion. Closing this now.

**Comment by rwjblue** [comment]
Awesome, glad you got it figured out!
