### ISSUE TITLE
upgrading to ember@2.18 and installing ember-test-helpers leaves module undefined during test hooks

### ISSUE THREAD

**Issue by BryanCrotaz** [ember-cli/ember-cli-qunit#205]
This seems like the same symptom as emberjs/ember-qunit#179.

Tests run in PhantomJS and every unit and integration test now fails with `undefined is not an object (evaluating 'module.setContext')`. A small number fail instead with `you must set a resolver with \`testResolver.set(resolver)\`` , but that's probably not `ember-cli-qunit`.

**Comment by rwjblue** [comment]
Can you provide a reproduction?

**Comment by BryanCrotaz** [comment]
I'm not sure how to - I've upgraded other projects and not seen this. I don't think they're using `ember-test-helpers` though.

It's a private repo - I could give you temporary access. It's a reasonably small addon - 70 tests,

**Comment by BryanCrotaz** [comment]
rebuilt from a new clean addon - installing `ember-test-helpers` is what breaks it. I'll reopen in there.
