### ISSUE TITLE
component integration test appened to body instead of inside div#ember-testing element

### ISSUE THREAD

**Issue by NullVoxPopuli** [ember-cli/ember-cli-qunit#207]
I discoverd this when trying to use the fancy `qunit-dom` helpers for checking if elements exist or if inputs have focus.

```ts
 // as-is, the test passes. 
 // but using the qunit-dom equivalents, no elements are ever found.
  test('click label | toggles editing', async function(assert) {
    assert.expect(4);

    this.set('testTodo', sampleTodo);
    await render(hbs`<Todo @todo={{testTodo}} />`);

    // qunit-dom specificatly looks in the root-element
    // whereas @ember/test-helpers looks in the body.
    // assert.dom(editingSelector).doesNotExist();
    // assert.dom(inputSelector).isNotFocused();
    //
    // await triggerEvent(labelSelector, 'click');
    //
    // assert.dom(editingSelector).exists();
    // assert.dom(inputSelector).isFocused();

    assert.notOk(find(editingSelector), 'nothing should be editing before any interaction');
    assert.isNotFocussed(find(inputSelector), 'input should not have focus when not editing');

    await triggerEvent(labelSelector, 'click');

    assert.ok(find(editingSelector), 'clicking the label should trigger editing');
    assert.isFocussed(find(inputSelector), 'input should have focus after the label is clicked');
  });
```

during debugging, I found the the `rootElement` for `@ember/test-helpers` differs from that of `qunit-dom` helpers.

in `qunit-dom`, the `rootElement` is the `div#ember-testing` element, but in `@ember/test-helpers` the `rootElement` is the `body`.

Here is a reproduction: https://github.com/NullVoxPopuli/react-vs-ember/blob/93615114df3d123caa7a0a3342f6da7d79be28a2/testing/ember/src/ui/components/todo/component-integration-test.ts#L21

**Comment by rwjblue** [comment]
This is likely due to opting in to the new `application-template-wrapper` optional feature: https://github.com/NullVoxPopuli/react-vs-ember/blob/93615114df3d123caa7a0a3342f6da7d79be28a2/testing/ember/config/optional-features.json#L2


you might dig into the code for detecting the root element and see if you spot the issue...

**Comment by NullVoxPopuli** [comment]
for find, this is what I'm seeing:
![image](https://user-images.githubusercontent.com/199018/41064348-4bacc4aa-69a9-11e8-94c1-1b3800964d1f.png)

the context owner is saying, "hey use me" instead of `#ember-testing`"
owner.rootElement is `body`. So that makes me think the problem is with the `owner`.

the owner / test context appears to be set before assertions happen (which is a good optimization)
![image](https://user-images.githubusercontent.com/199018/41064504-c3687f48-69a9-11e8-88a0-883ac6255996.png)

so, debugging render...
![image](https://user-images.githubusercontent.com/199018/41064566-ea1bf3ea-69a9-11e8-8ea6-25a4dfe7c5ae.png)
I see that it makes a similar call to getRootElement as find, which means that the rootElement (which is still body here) is set even earlier in the test process.

so, debugging _even earlier_ (at `setupRenderingTest()`), I finally see what looks to be setting the context:
![image](https://user-images.githubusercontent.com/199018/41064686-4ef544f6-69aa-11e8-8f3b-3dea4d3536c5.png)
But, context still has `body` as the rootElement.
![image](https://user-images.githubusercontent.com/199018/41064756-80c915c0-69aa-11e8-920e-7be62a33853a.png)

maybe inspecting `this` in the `setupRenderingTest(hooks)` call will shed some light.....
eventually, I find this:
![image](https://user-images.githubusercontent.com/199018/41065213-ea3bbd0e-69ab-11e8-999f-7f768782465a.png)
#ember-testing exists, and nothing is mounted in a weird place in the body. this seems like I finally got to an early enough place in the test-boot process. 

.... I somehow made my way to here:
![image](https://user-images.githubusercontent.com/199018/41065705-7d984f80-69ad-11e8-8a2b-73bef201ef8a.png)

(temp commenting, in case browser crashes...)

**Comment by NullVoxPopuli** [comment]
@rwjblue sure enough, this gets my test passing with qunit-dom helpers....

![image](https://user-images.githubusercontent.com/199018/41066783-275ff59c-69b1-11e8-91cc-5fb3f187a3d6.png)

so.... if this were a bug, what would it be on? or.. would it be a blueprint update? to say: 

```js
const App = Application.extend({
  modulePrefix: config.modulePrefix,
  podModulePrefix: config.podModulePrefix,
  rootElement: config.isTesting ? config.APP.rootElement : 'body',
  Resolver,
});
```
?

**Comment by rwjblue** [comment]
your tests/test-helpers.js is not setup correctly

**Comment by NullVoxPopuli** [comment]
Legit, I'll double check the module unification blueprint

**Comment by NullVoxPopuli** [comment]
https://github.com/ember-cli/ember-cli/pull/7867
