### ISSUE TITLE
Error wrt Babel while upgrading from 4.0.2 to 4.3.x

### ISSUE THREAD

**Issue by gokatz** [ember-cli/ember-cli-qunit#208]
When I tried to upgrade the ember-cli-qunit version from 4.02 to 4.3.x to use the new `triggerKeyEvent` API, I got the following issue wrt babel

```
index.js: Property object of MemberExpression expected node to be of a type ["Expression"] but instead got null
  - errorType: Build Error
  - location:
    - column: [undefined]
    - file: index.js
    - line: [undefined]
    - treeDir: /Users/gokul/opensource/ember-twiddle/tmp/broccoli_persistent_filterbabel-input_base_path-9febRdDo.tmp
  - message: Build Canceled: Broccoli Builder ran into an error with `Babel` plugin. 💥
index.js: Property object of MemberExpression expected node to be of a type ["Expression"] but instead got null
  - name: Error
  - nodeAnnotation: Babel
  - nodeName: Babel
  - originalErrorMessage: index.js: Property object of MemberExpression expected node to be of a type ["Expression"] but instead got null
  - stack: TypeError: index.js: Property object of MemberExpression expected node to be of a type ["Expression"] but instead got null
    at Object.validate (/Users/gokul/opensource/ember-twiddle/node_modules/babel-types/lib/definitions/index.js:109:13)
    at Object.validate (/Users/gokul/opensource/ember-twiddle/node_modules/babel-types/lib/index.js:505:9)
    at NodePath._replaceWith (/Users/gokul/opensource/ember-twiddle/node_modules/babel-traverse/lib/path/replacement.js:176:7)
    at NodePath._remove (/Users/gokul/opensource/ember-twiddle/node_modules/babel-traverse/lib/path/removal.js:58:10)
    at NodePath.remove (/Users/gokul/opensource/ember-twiddle/node_modules/babel-traverse/lib/path/removal.js:30:8)
    at PluginPass.CallExpression (/Users/gokul/opensource/ember-twiddle/node_modules/babel-plugin-transform-es2015-modules-amd/lib/index.js:42:12)
    at NodePath._call (/Users/gokul/opensource/ember-twiddle/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/Users/gokul/opensource/ember-twiddle/node_modules/babel-traverse/lib/path/context.js:48:17)
```

I getting this errror in ember-twiddle repo. Any suggestions ?

**Comment by rwjblue** [comment]
The only change was updating ember-cli-qunit?

**Comment by rwjblue** [comment]
As a complete guess, this looks to me like a usage of the global `require` method...

**Comment by rwjblue** [comment]
As an example of what I mean, see this PR https://github.com/ef4/ember-code-snippet/pull/33

**Comment by gokatz** [comment]
Thanks @rwjblue will check for any global requires

**Comment by gokatz** [comment]
we don't have explicit requires but [few embedded requires](https://github.com/ember-cli/ember-twiddle/blob/master/app/services/ember-cli.js#L399) in the repo. Even after commenting them out, the build fails with the same error 😬

**Comment by rwjblue** [comment]
I’d throw a breakpoint in there and see what it’s compiling. It _says_ it’s compiling `index.js` but unfortunately that isn’t super helpful...

**Comment by rwjblue** [comment]
I’m fairly sure this is not actually an issue in ember-cli-QUnit at this point. Is there an issue over in ember-twiddle tracking the update that we can use instead?

My guess is that the issue is stemming from the custom build code 

https://github.com/ember-cli/ember-twiddle/blob/383de91d26a3fa654a2b65c2115d64bdf74fa91c/ember-cli-build.js#L152

**Comment by gokatz** [comment]
> Is there an issue over in ember-twiddle tracking the update that we can use instead?

No, we haven't created any issue in twiddle repo as it is not the process of upgarding the deps. I needed a new API (`triggerKeyEvent`). So, decided to upgrade `ember-cli-qunit`.

> My guess is that the issue is stemming from the custom build code

Yeah, @rwjblue. The issue was due to requring `ember-qunit`. Tried `ember-cli-qunit` instead of `ember-qunit` and the build got succeeded.

**Comment by Gaurav0** [comment]
There is an earlier issue here: https://github.com/ember-cli/ember-twiddle/issues/600

Yes, we have embedded window.requires of ember-qunit. Is there an alternative for that?

**Comment by rwjblue** [comment]
@Gaurav0 - Ya, I linked a PR where I replaced `require`'s just above.  Basically you would `import require from 'require'` instead of using a `require` global.  Also, if you are already using `window.require` (as opposed to just using `require`) this won't be an issue for you.

**Comment by Gaurav0** [comment]
@rwjblue So switching to `window.require('ember-qunit')` didn't fix anything. I don't know if there is any way to recover the original version of require at runtime within the resulting index.html.

Anyway, the error @gokatz reported occurs at build time within `ember-cli-build.js`, not during the runtime build of a test.

**Comment by Gaurav0** [comment]
OK, the error is coming from this line in `ember-cli-build.js`:

`let finalQUnitTree = buildAddonTree('ember-qunit');`

and it is likely that I don't know how to build correctly this addon from outside ember-cli.

**Comment by Gaurav0** [comment]
@gokatz @rwjblue I've uploaded my branch here: https://github.com/Gaurav0/ember-twiddle/tree/gokatz-code-comment for anyone that would like to play with it.

**Comment by Gaurav0** [comment]
@gokatz So indeed, the issue was the way I was building ember-qunit was no longer compatible. `ember-qunit` went from being a simple npm module in 2.x to an ember addon in 3.x. It is no longer able to be made into a script tag importable version by simply transpiling and concatenating. It is now necessary to do a lot more.

The latest commits in the branch https://github.com/Gaurav0/ember-twiddle/tree/gokatz-code-comment seem to correctly build ember-qunit 3.x for importing from a script tag in a client application. Tests for tests are still broken, but I'll try to fix them later.

Generally, when working with Ember Twiddle, heavy use of private apis and nonstandard builds mean that semver is not a reliable guide as to whether a dependency is "safe" to upgrade.

@rwjblue This issue can be closed.

**Comment by rwjblue** [comment]
Great work @gaurav0, thanks for digging in.
