### ISSUE TITLE
Strange release number: v4.3.1 > v4.3.2 > v1.4.3 ?

### ISSUE THREAD

**Issue by HerveSeger** [ember-cli/ember-cli-qunit#209]
Hi.

is it normal that the latest release be `1.4.3` in `releases` after `4.3.2`?

**Comment by rwjblue** [comment]
Oh, you mean the GH releases page? That is quite literally sorted by date tagged, and there isn’t really a way for us to change that AFAICT. 

We legitimately had need to release a patch version of the super old 1.x branch a couple weeks ago, and haven’t released a 4.x again since....

**Comment by rwjblue** [comment]
No problem! Closing (since it isn’t an issue
per we)...
