### ISSUE TITLE
Global error: Uncaught SyntaxError: Failed to execute 'measure' on 'Performance': The mark 'qunit_test_start' does not exist.

### ISSUE THREAD

**Issue by afzal273** [ember-cli/ember-cli-qunit#213]
Since getting version 4.4.0 of `ember-cli-qunit`, getting this error -

Global error: Uncaught SyntaxError: Failed to execute 'measure' on 'Performance': The mark 'qunit_test_start' does not exist.

**Comment by rwjblue** [comment]
This issue is being tracked over in https://github.com/qunitjs/qunit/pull/1319 (see conversation over there for more details).

**Comment by stefanpenner** [comment]
QUnit fix landed `qunit@v2.7.1`
