### ISSUE TITLE
Deprecate npm package

### ISSUE THREAD

**Issue by bmish** [ember-cli/ember-cli-qunit#234]
Marking the package deprecated in the NPM registry will help increase visibility of the deprecation. Can the owner of this repository please run:

```
npm deprecate ember-cli-qunit "Use ember-qunit directly instead."
```

This deprecation is already mentioned in the README.

> NOTE: This addon has been deprecated! Please use ember-qunit directly instead.

**Comment by Turbo87** [comment]
done ✅
