### ISSUE TITLE
Pull QUnit From NPM Instead Of Bower

### ISSUE THREAD

**Issue by chadhietala** [ember-cli/ember-cli-qunit#26]
This probably requires https://github.com/ember-cli/ember-cli/pull/2381 and also @ef4's ember-browserify.

**Comment by rwjblue** [comment]
Why?  Is this an overall strategy (moving off of Bower) or just something for this library?  If this is a general strategy, then we should likely have an RFC to make the formal decision to switch our current default Bower deps to NPM deps (and potentially stop requiring Bower at all).

**Comment by chadhietala** [comment]
Yes, moving off of bower. I think we can get down to 1 package management system for "core" addons or libraries to see how it goes.  This just seems like low hanging fruit since QUnit is already published to NPM.  We can close for now if you would like.

**Comment by stefanpenner** [comment]
@chadhietala lets try this. I am also eager for a single package management system, ember-cli-qunit seems like as good a place as any to start.

**Comment by dgeb** [comment]
The dependency management strategies for npm and bower aren't compatible. From my perspective, neither is ideal (or even very good) but both have distinct advantages and disadvantages.

I'm not particularly nervous about pulling test support files from npm. However, once we get into assets that may be bundled for production, I think this deserves a larger discussion.

**Comment by Turbo87** [comment]
@chadhietala @rwjblue I think this issue has been resolved, right?

**Comment by trentmwillis** [comment]
Resolved as of #93.
