### ISSUE TITLE
Path or pattern "bower_components/ember-qunit/named-amd/main.js" did not match any files

### ISSUE THREAD

**Issue by zyllorion** [ember-cli/ember-cli-qunit#37]
Error when using latest ember-cli-qunit#0.3.3
```
Path or pattern "bower_components/ember-qunit/named-amd/main.js" did not match any files
```
Notes from discussion:
Something wrong with the internal `Blueprint.prototype.addBowerPackagesToProject`.
There really is no issue with using 0.3.3, the only thing that blueprint does is ensure you have bower.json setup properly.

Workaround:
```
bower install --save ember-qunit rwjblue/ember-qunit-builds#0.2.1
```

**Comment by rwjblue** [comment]
Thanks for reporting, this is definitely an issue.  It only cropped up after moving to `Blueprint.prototype.addBowerPackagesToProject` from `Blueprint.prototype.addBowerPackageToProject` (in https://github.com/ember-cli/ember-cli-qunit/pull/35).  I need to test to see if reverting that PR resolves the issue.
