### ISSUE TITLE
jQuery document ready not guaranteed to be available

### ISSUE THREAD

**Issue by gdub22** [ember-cli/ember-cli-qunit#40]
My ember-cli app uses a custom built, slimmed down jQuery where I exclude the core/ready module.  This causes tests to break because it assumes your app vendor.js's jQuery has the document.ready code.

https://github.com/ember-cli/ember-cli-qunit/blob/master/vendor/ember-cli-qunit/qunit-configuration.js#L16

**Comment by gdub22** [comment]
Still tracking this down... but works fine using v 0.2.0

**Comment by rwjblue** [comment]
I'd happily review/accept a PR replacing this with non-jQuery code, but we need to maintain IE8 compat if we do.

**Comment by gdub22** [comment]
#41 @rwjblue

**Comment by trentmwillis** [comment]
@rwjblue does this still need IE8 compat now? If not, we could switch to just using `DOMContentLoaded` as a simple fix forward.

**Comment by rwjblue** [comment]
We do still need to support IE8 unless we are saying that we do not support Ember 1.13 (and I think that would require a major bump).

**Comment by trentmwillis** [comment]
Closed via #136.
