### ISSUE TITLE
In model unit tests `this.subject().store` and `this.store()` are different

### ISSUE THREAD

**Issue by YoranBrondsema** [ember-cli/ember-cli-qunit#42]
I first posted this issue on the ember.js repository (https://github.com/emberjs/ember.js/issues/10367#issuecomment-73233420) but was told that it's almost certainly a bug in ember-cli-qunit.

See this discussion on StackOverflow: http://stackoverflow.com/a/25945287/1269194. In a model unit test, the `Store` objects returned by `this.subject().store` and `this.store()` are not the same, resulting in an error when trying to assign a model to a relationship.

For instance, say you have `Parent` and `Child` as follows:

````
Parent = DS.Model.extend({
    child: belongsTo('child')
});

Child = DS.Model.extend();
````

and in a unit test for `Parent` you do

````
this.subject().set('child', this.store().createRecord('child'));
````
then you get an error `Error: Assertion Failed: You can only add a 'child' record to this relationship`.

I encountered this bug when upgrading our non-ember-cli project to ember-cli 0.1.11.

**Comment by stefanpenner** [comment]
sounds like a bug

**Comment by YoranBrondsema** [comment]
Ok, it now seems that after upgrading from ember-data b12 to b14.1, the issue is resolved...
