### ISSUE TITLE
The testing css breaks getClientBoundingRect with non standards compliant css

### ISSUE THREAD

**Issue by krisselden** [ember-cli/ember-cli-qunit#48]
The css `zoom: 50%` is non standards compliant and breaks code that uses getClientBoundingRect.  If we want to scale the testing container, we should use css transforms `transform: scale(0.5 0.5)` which is correctly accounted for in getClientBoundingRect.

**Comment by trentmwillis** [comment]
Fixed via #123 and released in 2.1.0

**Comment by rwjblue** [comment]
Oops, looks like that last comment was off.  This was fixed by https://github.com/ember-cli/ember-cli-qunit/pull/120 (not #123).
