### ISSUE TITLE
Updated broccoli-jshint to 0.5.6

### ISSUE THREAD

**Issue by vuhrmeister** [ember-cli/ember-cli-qunit#66]
This version fixes the following issue: https://github.com/ember-cli/ember-cli/issues/3624

**Comment by nojacko** [comment]
I've submitted a pull request for this. https://github.com/ember-cli/ember-cli-qunit/pull/67

**Comment by stefanpenner** [comment]
@rwjblue can you cut a release. Currently on my phone

**Comment by rwjblue** [comment]
Published 0.3.14.

**Comment by stefanpenner** [comment]
danke
