### ISSUE TITLE
jshint no longer skips

### ISSUE THREAD

**Issue by stefanpenner** [ember-cli/ember-cli-qunit#74]

**Comment by rwjblue** [comment]
I'm a little confused by the title here. Lemme know when you flesh this out more and I can help track down whats going on...

**Comment by stefanpenner** [comment]
will do.

details for now: we just upgraded to 1.0.0, and the `hinting: false` in EmberApp no longer prevents hinting.

Note: CLI was not updated, only this addon.

**Comment by stefanpenner** [comment]
may actually just be related to an ember-cli vs jshint incompat, confirming

**Comment by stefanpenner** [comment]
works fine with latest cli
