### ISSUE TITLE
rootElement isn't expressive enough.

### ISSUE THREAD

**Issue by nathanhammond** [ember-cli/ember-cli-qunit#81]
We need both `rootElement` and `options[‘ember-cli-qunit’].rootElement`. We can’t continue to overload the one. It results in us forcing the config to have a different environment as we’re building the test tree and makes it very difficult to gracefully extend testing behavior on an environmental basis. Anybody opposed?

I'll build it if there's interest and find some way to make it backward-compatible.

/cc @rwjblue @stefanpenner

**Comment by rwjblue** [comment]
I am unsure if I am opposed.

Can you please explain:

* what the specific issue you are attempting to address
* what makes the current system fall down in your scenario
* other things?

**Comment by nathanhammond** [comment]
So, considering this:
https://github.com/nathanhammond/ember-capture/commit/a7054f14fda9f6cd85174ac2c929ef344b908528

My goal is to be able to configure the `rootElement` for just the `capture` environment, and have that apply when running tests in the `capture` environment. However, since we’re forcing the tests to ​_always_​ be built in the `test` environment, I have to override behavior generically for the `test` environment.

This means that if you include `ember-capture` right now you’re having your `rootElement` for the `test` environment set by `ember-capture`, and there’s not really much I can do about it. This means that you never get the existing behavior for tests once you adopt something that wants to (significantly modify) our testing setup.

We’re effectively leaking the configuration from our `test` environment into all of the other environments. This feels wrong.

**Comment by trentmwillis** [comment]
Closing this as it seems to have gone stale and there doesn't seem to be immediately actionable items.
