### ISSUE TITLE
Can't find local modules

### ISSUE THREAD

**Issue by barneycarroll** [ember-cli/ember-cli-qunit#90]
It seems Ember tests can't resolve local modules. Despite being aware of the import mechanism, surrounding project filesystem and resolving paths correctly, I will always receive ``Error: Could not find module `${project-name}/{path-to-my-module}` `` if I try to import anything local.

**Comment by rwjblue** [comment]
Need more info:

* Why do you think it is related to ember-cli-qunit?
* What is the actual `import` statement you are using?
* Where are the files on disk you are trying to import?

**Comment by barneycarroll** [comment]
Thanks for the prompt response. 

> * Why do you think it is related to ember-cli-qunit

Good question. I've been dealing with projects with explicit dependencies for a while, and the monolithic framework approach favoured by Ember (especially with the CLI) throws me a bit because of all the implicit dependency invocations and reference resolution magic. imports work in my application proper, but don't work in tests. However when I tried to reproduce a minimal test case and… [it just works](https://github.com/barneycarroll/ember-test-local-import)!

I'll close this until I can get any kind of more meaningful feedback on why my app can't do this if it points to a problem in qunit instantiation - but from scouring the source, I doubt it is. There is no special dependency resolution magic in this package at all, is there? Thanks again.
