### ISSUE TITLE
Bumping to 1.1.0 stops tests from running

### ISSUE THREAD

**Issue by oliverwilkie** [ember-cli/ember-cli-qunit#95]
Ember CLI version: 1.13.13

Bumping from `1.0.5` to `1.1.0` stops my tests from running with the following output

I made sure I deleted `ember-qunit` 

```
Error: Assertion Failed: The tests file was not loaded. Make sure your tests index.html i
ncludes "assets/tests.js". at http://localhost:7357/assets/vendor.js, line 16471
Error: Could not find module `ember-qunit` imported from `dispatcher/tests/test-helper` a
t http://localhost:7357/assets/vendor.js, line 144
```

Let me know what else I can provide.

**Comment by rwjblue** [comment]
Can you create an empty repo that demonstrates the issue?  I'd love to dig in, and a reproduction will be very helpful...

**Comment by oliverwilkie** [comment]
Of course, here it is `https://github.com/oliverwilkie/dispatcher` (I basically just did an `ember init` and then copied my test files and package.json and bower.json over)

**Comment by oliverwilkie** [comment]
Check that out `ember test --server` using 1.13.13 and you should get the same message

**Comment by rwjblue** [comment]
Awesome, thank you!  Will try to look soon.

**Comment by duboff** [comment]
Same problem

**Comment by stefanpenner** [comment]
> Of course, here it is [https://github.com/oliverwilkie/dispatcher] .I basically just did an ember init and then copied my test files and package.json and bower.json over

@oliverwilkie this app is crashing by default, because it does not have a fully installed ember-cli-mirage. Please be sure your reproduction is for the issue you have.

**Comment by stefanpenner** [comment]
> Error: Could not find module `ember-qunit` imported from `dispatcher/tests/test-helper` a
> t http://localhost:7357/assets/vendor.js, line 144

this error appears to be a side-affect of another error, scrolling up we see.
![screen shot 2016-01-04 at 9 04 38 am](https://cloud.githubusercontent.com/assets/1377/12095243/38662f30-b2c2-11e5-9fba-c01928152ad7.png)

Which indicates someone is trying to `require` without a name.

**Comment by stefanpenner** [comment]
@duboff something in your vendor.js is crashing, likely do to syntax error or some other runtime error. Please investigate that thoroughly If you cannot figure it out, please open a new discrete issue with a reproduction.

**Comment by duboff** [comment]
Yeah, I figured our issue is different but cannot reproduce it now. Probably one of the other addons

**Comment by stefanpenner** [comment]
@oliverwilkie  source of the issue appears to be something in `ember-cli-mock-socket` without it, everything seems to work correctly.

This does not appear to be an ember-cli issue, rather something funky with an upstream dependency. Unfortunately we do not have the capacity to consider what appears to be a bug in a non-default package addon. If it turns out something is wrong in ember-cli we can reopen.

**Comment by stefanpenner** [comment]
My quick guess is that an upgraded mock-socket would fix it. as it appears to have relevant changes since the version bundled with ember-cli-mock-socket was released.

**Comment by oliverwilkie** [comment]
Thanks for looking into it!
