### ISSUE TITLE
`lodash-node` deprecated (from old version of `broccoli-sourcemap-concat`)

### ISSUE THREAD

**Issue by gabrielgrant** [ember-cli/ember-cli-qunit#98]
Getting the following warning when installing ember-cli:

```
$ npm install -g ember-cli@2.2.0-beta.3
npm WARN deprecated lodash-node@2.4.1: This package is no longer maintained. See its readme for upgrade details.
```

One cause seems to be that `ember-cli-qunit` is [pegged to old an version of `broccoli-sourcemap-concat`](https://github.com/ember-cli/ember-cli-qunit/blob/master/package.json#L31) which depends on `lodash-node`

Is there some reason the old version is needed? Or can the dep be upgraded to either the most recent version (2.0.2) or to use [broccoli-concat](https://github.com/ember-cli/broccoli-concat)? (probably preferable, since `broccoli-sourcemap-concat`  was [recently deprecated in it's favor](https://github.com/ef4/broccoli-sourcemap-concat/issues/36))

**Comment by trentmwillis** [comment]
This looks to have been resolved with #107.
